
---

## **Screenshot**
![Label Preview](images/label-example.png) 

---

## **Notes**
- Best viewed in modern browsers.  
- No installation required. Just open `index.html`.  

---

## **License**
Internal use only – not for public distribution.
